# Generated by Django 5.0.1 on 2024-01-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caption_generator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
