# Generated by Django 5.0.1 on 2024-01-30 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption_generator', '0007_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('imageId', models.AutoField(primary_key=True, serialize=False)),
                ('imagefileName', models.CharField(max_length=255)),
                ('Uploadtimestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('captionId', models.AutoField(primary_key=True, serialize=False)),
                ('captiontext', models.TextField()),
                ('captionTimestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caption_generator.image')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
