# Generated by Django 5.0.1 on 2024-02-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption_generator', '0008_image_caption_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='imagefileName',
            new_name='imagefileNname',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
    ]
