# Generated by Django 5.0.1 on 2024-02-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption_generator', '0011_alter_caption_captionid_alter_image_imageid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caption',
            name='captionId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='imageId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
